### PR TITLE
Shift-double-click to add marker.

### PR DESCRIPTION
**Pull request by WardCunningham**
These commits add a keystroke command that adds a marker to a map. This enables several more workflows that make cataloging geographic information go smoothly. 

image
http://home.ward.asia.wiki.org/places-ive-lived.html

### CODE REVIEW

**Comment by paul90** [comment]
Not sure what is happening, but I can’t see this pull request on the web site… Also getting errors trying to access clemsos/wiki-plugin-map, which might be related.

**Comment by WardCunningham** [comment]
Github support writes, "Sorry about that! It appears our system incorrectly flagged your account. I've removed that flag, and you shouldn't see it again."

screen shot 2016-07-11 at 2 54 43 pm

**Comment by paul90** [comment]
That was weird - good that has been resolved. Will try and look at this pull request later today

**Comment by paul90** [comment]
Published as + wiki-plugin-map@0.3.1

**Pull request merged**
