### PR TITLE
add overlay maps

### PR DESCRIPTION
**Pull request by WardCunningham**
Leaflet is happy to [overlay images](https://leafletjs.com/reference-1.4.0.html#imageoverlay) so we add that capability with specialized markup.

image

Here we overlay the George Fox University [campus map](https://www.georgefox.edu/maps_locations/inter_map/campus-map.pdf) within the city of Newberg, Oregon and then locate the Engineering Maker Hub on that map with a clickable marker.

### CODE REVIEW

**Comment by WardCunningham** [comment]
> Not sure when or how, but the fixing of the mouse-grabbing of the map plugin was a life-saver. The interaction is not perfect but workable now - although mobile is tricky - ideally we want to be able to fix a map so it is not able to scroll and enable a full screen mode (or link to a new tab) where we can scroll in the map.

@fortyfoxes: Please explain what behavior is different with the map plugin. It was not my intention to change anything other than adding the overlay. Some Leaflet expertise would be helpful.

**Comment by paul90** [comment]
Looks as if David is referring to a behaviour that was resolved in 5f04e6664607fd69dd249ed1d0e900b9a9f8162a  (June 2018). If I remember correctly this was made possible thanks to upgrading to a newer version of Leaflet.

**Comment by WardCunningham** [comment]
> For the decimal notation the point example has a space after the comma. Having a space after the coma is not allowed by the current OVERLAY. I think it would be an idea to allow a space. What do you think?

I agree. With such a long command it is still a good idea to use space sparingly.  I was feeling that I was overly generous with the other regular expressions.

**Comment by paul90** [comment]
Published as + wiki-plugin-map@0.3.6

**Pull request merged**
